import { QUIZ } from './quiz-data.js';
import { TEXT_CONFIG } from './text-config.js';
const KEY='nici40QuizConfigV1';
const VERSION=2;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function defaults(){return QUIZ.flatMap((round,ri)=>round.items.map((item,qi)=>({id:`${ri}-${qi}`,enabled:true,roundName:round.name,theme:round.theme,cat:item.cat||'POP',originalQ:item.q,q:item.q,options:[...item.o],answerIndex:item.a,explanation:item.e||'',answerMode:TEXT_CONFIG[item.q]?'open':'mc',canonical:TEXT_CONFIG[item.q]?.canonical||item.o[item.a],accept:TEXT_CONFIG[item.q]?.accept||[item.o[item.a]]})))}
function sanitizeSeconds(v){const n=Math.round(Number(v)||180);return Math.max(15,Math.min(600,n))}
function normalizeItem(x,base){const b=base||{};const options=Array.isArray(x?.options)?x.options.slice(0,4).map(v=>String(v)):Array.isArray(b.options)?[...b.options]:['','','',''];while(options.length<4)options.push('');const answerIndex=Math.max(0,Math.min(3,Number.isInteger(Number(x?.answerIndex))?Number(x.answerIndex):Number(b.answerIndex)||0));return{id:String(x?.id??b.id??''),enabled:x?.enabled!==false,roundName:String(x?.roundName??b.roundName??'Quiz'),theme:String(x?.theme??b.theme??'80s'),cat:String(x?.cat??b.cat??'POP'),originalQ:String(x?.originalQ??b.originalQ??x?.q??b.q??''),q:String(x?.q??b.q??'Frage'),options,answerIndex,explanation:String(x?.explanation??b.explanation??''),answerMode:x?.answerMode==='open'?'open':'mc',canonical:String(x?.canonical??b.canonical??options[answerIndex]??''),accept:Array.isArray(x?.accept)?x.accept.map(String):Array.isArray(b.accept)?[...b.accept]:[String(x?.canonical??options[answerIndex]??'')]}}
function defaultConfig(){return{version:VERSION,settings:{questionSeconds:180},items:defaults()}}
function normalizeConfig(raw){const d=defaultConfig();if(Array.isArray(raw)){return{version:VERSION,settings:{questionSeconds:180},items:raw.map((x,i)=>normalizeItem(x,d.items[i])).filter(x=>x.id)}}if(!raw||typeof raw!=='object')return d;const src=Array.isArray(raw.items)?raw.items:[];const byId=new Map(d.items.map(x=>[x.id,x]));const normalized=src.map(x=>normalizeItem(x,byId.get(String(x?.id)))).filter(x=>x.id);return{version:VERSION,settings:{questionSeconds:sanitizeSeconds(raw.settings?.questionSeconds)},items:normalized.length?normalized:d.items}}
function load(){try{return normalizeConfig(JSON.parse(localStorage.getItem(KEY)||'null'))}catch{return defaultConfig()}}
let config=load(),items=config.items;
const root=document.querySelector('#questionAdmin'),count=document.querySelector('#activeCount'),status=document.querySelector('#saveStatus'),secondsInput=document.querySelector('#questionSeconds');
secondsInput.value=config.settings.questionSeconds;
function syncCount(){count.textContent=items.filter(x=>x.enabled).length}
function syncSettings(){config.settings.questionSeconds=sanitizeSeconds(secondsInput.value);secondsInput.value=config.settings.questionSeconds}
function render(){root.innerHTML='';for(const theme of ['80s','90s','00s','10s','20s']){const group=items.filter(x=>x.theme===theme);if(!group.length)continue;const sec=document.createElement('section');sec.className='panel adminEra';sec.innerHTML=`<div class="eraHead"><div><div class="eyebrow">${esc(group[0].roundName)}</div><h2>${esc(group[0].roundName)} POP CULTURE</h2></div><span>${group.filter(x=>x.enabled).length}/${group.length} aktiv</span></div><div class="questionGrid"></div>`;const grid=sec.querySelector('.questionGrid');for(const x of group){const card=document.createElement('article');card.className=`adminQuestion ${x.enabled?'enabled':'disabled'}`;card.innerHTML=`<div class="questionHead"><label class="toggleLine"><input data-k="enabled" type="checkbox" ${x.enabled?'checked':''}><span>AKTIV</span></label><span class="catBadge">${esc(x.cat)}</span><select data-k="answerMode"><option value="mc" ${x.answerMode==='mc'?'selected':''}>Multiple Choice</option><option value="open" ${x.answerMode==='open'?'selected':''}>Offene Antwort + KI</option></select></div><label>Fragetext<textarea data-k="q" rows="2">${esc(x.q)}</textarea></label><div class="mcEditor ${x.answerMode==='mc'?'':'dim'}"><div class="editorLabel">Antwortmöglichkeiten · richtige Antwort markieren</div>${x.options.map((o,i)=>`<label class="optionEdit"><input type="radio" name="correct-${x.id}" data-answer="${i}" ${i===x.answerIndex?'checked':''}><span>${String.fromCharCode(65+i)}</span><input data-option="${i}" value="${esc(o)}"></label>`).join('')}</div><div class="openEditor ${x.answerMode==='open'?'':'dim'}"><label>Erwartete Lösung<input data-k="canonical" value="${esc(x.canonical)}"></label><small>KI akzeptiert zusätzlich sinnvolle Varianten und Tippfehler.</small></div></article>`;card.addEventListener('input',e=>{const t=e.target;if(t.dataset.k==='enabled'){x.enabled=t.checked;card.classList.toggle('enabled',x.enabled);card.classList.toggle('disabled',!x.enabled)}else if(t.dataset.k==='answerMode'){x.answerMode=t.value;card.querySelector('.mcEditor').classList.toggle('dim',x.answerMode!=='mc');card.querySelector('.openEditor').classList.toggle('dim',x.answerMode!=='open')}else if(t.dataset.k){x[t.dataset.k]=t.value}else if(t.dataset.option!=null){x.options[Number(t.dataset.option)]=t.value;if(Number(t.dataset.option)===x.answerIndex&&x.answerMode==='mc')x.canonical=t.value}else if(t.dataset.answer!=null){x.answerIndex=Number(t.dataset.answer);x.canonical=x.options[x.answerIndex];card.querySelector('[data-k="canonical"]').value=x.canonical}syncCount();sec.querySelector('.eraHead span').textContent=`${group.filter(y=>y.enabled).length}/${group.length} aktiv`});grid.appendChild(card)}root.appendChild(sec)}syncCount()}
function persist(show=true){syncSettings();config={version:VERSION,settings:{...config.settings},items};localStorage.setItem(KEY,JSON.stringify(config));if(show){status.textContent=`✓ Gespeichert · ${items.filter(x=>x.enabled).length} Fragen · ${config.settings.questionSeconds} s pro Frage.`;setTimeout(()=>status.textContent='',3000)}}
function exportConfig(){persist(false);const payload={app:'Nicole40-TimeWarp-Quiz',version:VERSION,exportedAt:new Date().toISOString(),settings:config.settings,items};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`nicole40-quiz-config-${new Date().toISOString().slice(0,10)}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500);status.textContent='✓ Konfiguration als Datei exportiert.'}
async function importConfig(file){if(!file)return;try{const raw=JSON.parse(await file.text());const next=normalizeConfig(raw);if(!next.items.length)throw new Error('Keine Fragen gefunden');config=next;items=config.items;secondsInput.value=config.settings.questionSeconds;persist(false);render();status.textContent=`✓ Importiert · ${items.filter(x=>x.enabled).length} Fragen · ${config.settings.questionSeconds} s pro Frage.`}catch(e){status.textContent=`✗ Import fehlgeschlagen: ${e.message||'ungültige Datei'}`}}
document.querySelector('#allOn').onclick=()=>{items.forEach(x=>x.enabled=true);render()};document.querySelector('#allOff').onclick=()=>{items.forEach(x=>x.enabled=false);render()};document.querySelector('#resetAll').onclick=()=>{if(confirm('Alle Änderungen auf Standard zurücksetzen?')){config=defaultConfig();items=config.items;secondsInput.value=config.settings.questionSeconds;localStorage.removeItem(KEY);render();status.textContent='Standard wiederhergestellt.'}};document.querySelector('#saveAll').onclick=()=>persist(true);document.querySelector('#exportConfig').onclick=exportConfig;document.querySelector('#importConfig').addEventListener('change',e=>{importConfig(e.target.files?.[0]);e.target.value=''});secondsInput.addEventListener('change',()=>{syncSettings();status.textContent=`Zeit: ${config.settings.questionSeconds} Sekunden pro Frage.`});document.querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>{secondsInput.value=b.dataset.time;syncSettings()});window.addEventListener('beforeunload',()=>persist(false));render();