import { QUIZ } from './quiz-data.js';
import { TEXT_CONFIG } from './text-config.js';
const KEY='nici40QuizConfigV1';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function defaults(){return QUIZ.flatMap((round,ri)=>round.items.map((item,qi)=>({id:`${ri}-${qi}`,enabled:true,roundName:round.name,theme:round.theme,cat:item.cat||'POP',originalQ:item.q,q:item.q,options:[...item.o],answerIndex:item.a,explanation:item.e||'',answerMode:TEXT_CONFIG[item.q]?'open':'mc',canonical:TEXT_CONFIG[item.q]?.canonical||item.o[item.a],accept:TEXT_CONFIG[item.q]?.accept||[item.o[item.a]]})))}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(Array.isArray(x)&&x.length)return x}catch{}return defaults()}
let items=load();
const root=document.querySelector('#questionAdmin'),count=document.querySelector('#activeCount'),status=document.querySelector('#saveStatus');
function syncCount(){count.textContent=items.filter(x=>x.enabled).length}
function render(){root.innerHTML='';for(const theme of ['80s','90s','00s','10s','20s']){const group=items.filter(x=>x.theme===theme);if(!group.length)continue;const sec=document.createElement('section');sec.className='panel adminEra';sec.innerHTML=`<div class="eraHead"><div><div class="eyebrow">${esc(group[0].roundName)}</div><h2>${esc(group[0].roundName)} POP CULTURE</h2></div><span>${group.filter(x=>x.enabled).length}/${group.length} aktiv</span></div><div class="questionGrid"></div>`;const grid=sec.querySelector('.questionGrid');for(const x of group){const idx=items.indexOf(x);const card=document.createElement('article');card.className=`adminQuestion ${x.enabled?'enabled':'disabled'}`;card.innerHTML=`<div class="questionHead"><label class="toggleLine"><input data-k="enabled" type="checkbox" ${x.enabled?'checked':''}><span>AKTIV</span></label><span class="catBadge">${esc(x.cat)}</span><select data-k="answerMode"><option value="mc" ${x.answerMode==='mc'?'selected':''}>Multiple Choice</option><option value="open" ${x.answerMode==='open'?'selected':''}>Offene Antwort + KI</option></select></div><label>Fragetext<textarea data-k="q" rows="2">${esc(x.q)}</textarea></label><div class="mcEditor ${x.answerMode==='mc'?'':'dim'}"><div class="editorLabel">Antwortmöglichkeiten · richtige Antwort markieren</div>${x.options.map((o,i)=>`<label class="optionEdit"><input type="radio" name="correct-${x.id}" data-answer="${i}" ${i===x.answerIndex?'checked':''}><span>${String.fromCharCode(65+i)}</span><input data-option="${i}" value="${esc(o)}"></label>`).join('')}</div><div class="openEditor ${x.answerMode==='open'?'':'dim'}"><label>Erwartete Lösung<input data-k="canonical" value="${esc(x.canonical)}"></label><small>KI akzeptiert zusätzlich sinnvolle Varianten und Tippfehler.</small></div></article>`;card.addEventListener('input',e=>{const t=e.target;if(t.dataset.k==='enabled'){x.enabled=t.checked;card.classList.toggle('enabled',x.enabled);card.classList.toggle('disabled',!x.enabled)}else if(t.dataset.k==='answerMode'){x.answerMode=t.value;card.querySelector('.mcEditor').classList.toggle('dim',x.answerMode!=='mc');card.querySelector('.openEditor').classList.toggle('dim',x.answerMode!=='open')}else if(t.dataset.k){x[t.dataset.k]=t.value}else if(t.dataset.option!=null){x.options[Number(t.dataset.option)]=t.value}else if(t.dataset.answer!=null){x.answerIndex=Number(t.dataset.answer);x.canonical=x.options[x.answerIndex];card.querySelector('[data-k="canonical"]').value=x.canonical}syncCount();sec.querySelector('.eraHead span').textContent=`${group.filter(y=>y.enabled).length}/${group.length} aktiv`});grid.appendChild(card)}root.appendChild(sec)}syncCount()}
function save(){localStorage.setItem(KEY,JSON.stringify(items));status.textContent=`✓ Gespeichert · ${items.filter(x=>x.enabled).length} Fragen werden beim nächsten Spiel verwendet.`;setTimeout(()=>status.textContent='',3000)}
document.querySelector('#allOn').onclick=()=>{items.forEach(x=>x.enabled=true);render()};document.querySelector('#allOff').onclick=()=>{items.forEach(x=>x.enabled=false);render()};document.querySelector('#resetAll').onclick=()=>{if(confirm('Alle Änderungen auf Standard zurücksetzen?')){items=defaults();localStorage.removeItem(KEY);render();status.textContent='Standard wiederhergestellt.'}};document.querySelector('#saveAll').onclick=save;window.addEventListener('beforeunload',()=>localStorage.setItem(KEY,JSON.stringify(items)));render();