import { QUIZ, FLAT } from './quiz-data.js';
let ws,state,role=null,playerId=null,hostToken=localStorage.hostToken||'',roomCode=localStorage.roomCode||'',selected=null,timerLoop=null;
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
window.createGame=createGame;window.showJoin=showJoin;window.joinGame=joinGame;window.send=send;window.answer=answer;window.nextHost=nextHost;window.prevHost=prevHost;
function connect(cb){const proto=location.protocol==='https:'?'wss':'ws';ws=new WebSocket(`${proto}://${location.host}/ws`);ws.onopen=()=>{$('#status').textContent='ONLINE';cb&&cb()};ws.onclose=()=>{$('#status').textContent='SIGNAL LOST';setTimeout(()=>{if(role==='host'&&roomCode&&hostToken)connect(()=>send('rejoinHost',{code:roomCode,hostToken}))},1500)};ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='error')return alert(m.message);if(m.type==='created'){role='host';roomCode=m.code;hostToken=m.hostToken;localStorage.roomCode=roomCode;localStorage.hostToken=hostToken;state=m.state;render()}if(m.type==='joined'){role='player';playerId=m.playerId;state=m.state;render()}if(m.type==='state'){state=m.state;render()}if(m.type==='answerAccepted'){selected=m.answer;render()}}}
function send(type,x={}){if(ws?.readyState===1)ws.send(JSON.stringify({type,...x}))}
function showJoin(){$('#joinBox').classList.remove('hidden')}
function createGame(mode='pub'){connect(()=>send('create',{mode}))}
function joinGame(){const code=$('#code').value.trim().toUpperCase(),name=$('#name').value.trim();if(!code||!name)return alert('Code und Teamname eingeben.');connect(()=>send('join',{code,name}))}
function current(){return QUIZ[state.roundIndex]?.items[state.questionIndex]}
function flatCurrent(){return FLAT.findIndex(x=>x.roundIndex===state.roundIndex&&x.questionIndex===state.questionIndex)}
function render(){if(!state)return;$('#home').classList.add('hidden');applyEra();if(role==='host')renderHost();else renderPlayer();startTimerLoop()}
let lastEra=null;function applyEra(){const era=QUIZ[state.roundIndex]?.theme||'80s';document.body.dataset.era=era;document.querySelectorAll('.timeline .era').forEach((el,i)=>el.classList.toggle('active',i===state.roundIndex));if(lastEra&&lastEra!==era){const names={'80s':'1980s','90s':'1990s','00s':'2000s','10s':'2010s','20s':'2020s'},subs={'80s':'PRESS PLAY ▶','90s':'START → PROGRAMS → QUIZ','00s':'● MESSENGER STATUS: ONLINE','10s':'SWIPE TO CONTINUE →','20s':'NEXT ERA LOADING…'};const o=document.getElementById('eraTransition');if(o){document.getElementById('eraTransitionTitle').textContent=names[era];document.getElementById('eraTransitionSub').textContent=subs[era];o.classList.add('show');setTimeout(()=>o.classList.remove('show'),2600)}}lastEra=era;}
function startTimerLoop(){clearInterval(timerLoop);if(state?.mode!=='pub'||state.phase!=='playing'||!state.questionEndsAt)return;updateTimers();timerLoop=setInterval(updateTimers,250)}
function timeLeft(){return Math.max(0,state.questionEndsAt-Date.now())}
function fmt(ms){const total=Math.ceil(ms/1000),m=Math.floor(total/60),s=total%60;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function timerHTML(){const left=timeLeft(),pct=Math.max(0,Math.min(100,left/180000*100));return `<div class="timerWrap"><div><div class="timerLabel">TIME REMAINING</div><div class="timer ${left<30000?'danger':''}" data-timer>${fmt(left)}</div></div></div><div class="timerBar"><div data-timerbar style="width:${pct}%"></div></div>`}
function updateTimers(){const left=timeLeft(),pct=Math.max(0,Math.min(100,left/180000*100));document.querySelectorAll('[data-timer]').forEach(el=>{el.textContent=fmt(left);el.classList.toggle('danger',left<30000)});document.querySelectorAll('[data-timerbar]').forEach(el=>el.style.width=pct+'%')}
function playersHTML(host=false){if(!state.players.length)return '<p class="muted">Noch niemand da.</p>';return [...state.players].sort((a,b)=>(b.score??0)-(a.score??0)).map(p=>`<div class="playerRow"><span>${esc(p.name)} ${p.answered?'✓':''}</span><span>${state.mode==='pub'&&state.phase!=='finished'?'<b>•••</b>':`<b>${p.score??0}</b>`}${host&&state.mode==='live'?`<span class="scoreBtns"><button onclick="send('score',{playerId:'${p.id}',delta:1})">+1</button><button onclick="send('score',{playerId:'${p.id}',delta:2})">+2</button><button onclick="send('score',{playerId:'${p.id}',delta:-1})">−1</button></span>`:''}</span></div>`).join('')}
function renderHost(){
 $('#host').classList.remove('hidden');$('#player').classList.add('hidden');$('#bigCode').textContent=state.code;$('#modeBadge').textContent=state.mode==='pub'?'PUB MODE // 03:00 JE FRAGE':'LIVE MODE';$('#hostPlayers').innerHTML=playersHTML(true);
 if(state.phase==='lobby'){$('#hostControls').innerHTML=`<button class="primary" onclick="send('start')">START GAME</button>`;$('#hostQuestion').innerHTML=`<div class="center"><div class="phaseBanner">WAITING FOR PLAYERS</div><h2 class="waitingPulse">PRESS START WHEN READY</h2><p class="muted">Alle öffnen diese Seite und treten mit dem Code <b>${state.code}</b> bei.</p>${state.mode==='pub'?'<div class="answerBox">PUB MODE: Jede Frage läuft 3:00 Minuten. Während des Quiz gibt es keine Lösungen und keinen Zwischenstand. Die komplette Auflösung kommt erst nach der letzten Frage.</div>':''}</div>`;return}
 if(state.phase==='review')return renderReview(true);
 if(state.phase==='finished')return renderFinal(true);
 const item=current(),round=QUIZ[state.roundIndex],idx=flatCurrent();
 if(state.mode==='pub'){$('#hostControls').innerHTML=`<button onclick="send('pubNext')">FRAGE BEENDEN →</button>`;$('#hostQuestion').innerHTML=`<div class="phaseBanner">QUESTION ${idx+1} / ${FLAT.length}</div>${timerHTML()}<div class="eyebrow">${esc(round.name)}</div><div class="question">${esc(item.q)}</div><div class="opts">${item.o.map((o,i)=>`<div class="opt">${String.fromCharCode(65+i)} · ${esc(o)}</div>`).join('')}</div><div class="answerBox"><b>${state.players.filter(p=>p.answered).length}/${state.players.length}</b> Teams haben geantwortet. Lösungen bleiben bis zur Auflösungsrunde gesperrt.</div>`;return}
 $('#hostControls').innerHTML=`<button onclick="prevHost()">←</button><button class="primary" onclick="send('reveal')">AUFLÖSEN</button><button onclick="nextHost()">WEITER →</button><button onclick="send('finish')">ENDE</button>`;$('#hostQuestion').innerHTML=`<div class="eyebrow">${esc(round.name)} · ${state.questionIndex+1}/${round.items.length}</div><div class="question">${esc(item.q)}</div><div class="opts">${item.o.map((o,i)=>`<div class="opt ${state.revealed&&i===item.a?'correct':''}">${String.fromCharCode(65+i)} · ${esc(o)}</div>`).join('')}</div>${state.revealed?`<div class="answerBox"><b>AUFLÖSUNG:</b> ${esc(item.o[item.a])}<br><span class="muted">${esc(item.e)}</span></div>`:''}`;
}
function renderPlayer(){
 $('#player').classList.remove('hidden');$('#host').classList.add('hidden');const me=state.players.find(p=>p.id===playerId);$('#playerName').textContent=me?.name||'TEAM';
 if(state.phase==='lobby')return $('#playerView').innerHTML=`<div class="center"><h2>READY ✓</h2><p class="muted">CODE ${state.code} // Warte auf den Host.</p></div>`;
 if(state.phase==='review')return renderReview(false);
 if(state.phase==='finished')return renderFinal(false);
 const item=current(),round=QUIZ[state.roundIndex],idx=flatCurrent();if(!me?.answered)selected=null;
 $('#playerView').innerHTML=`${state.mode==='pub'?`<div class="phaseBanner">QUESTION ${idx+1} / ${FLAT.length}</div>${timerHTML()}`:''}<div class="eyebrow">${esc(round.name)}</div><div class="question">${esc(item.q)}</div><div class="opts">${item.o.map((o,i)=>`<button class="opt ${selected===i?'selected':''} ${state.revealed&&i===item.a?'correct':''}" ${me?.answered||state.revealed?'disabled':''} onclick="answer(${i})">${String.fromCharCode(65+i)} · ${esc(o)}</button>`).join('')}</div>${me?.answered&&!state.revealed?'<div class="answerBox">LOCKED IN ✓<br><span class="muted">Antwort gespeichert. Bis zum Ende bleibt geheim, ob sie stimmt.</span></div>':''}${state.revealed?`<div class="answerBox"><b>${esc(item.o[item.a])}</b><br><span class="muted">${esc(item.e)}</span></div>`:''}`;
}
function renderReview(host){const x=FLAT[state.reviewIndex]||FLAT[0];const body=`<div class="phaseBanner">ANSWER REVEAL</div><div class="reviewCount">AUFLÖSUNG ${state.reviewIndex+1} / ${FLAT.length}</div><div class="eyebrow">${esc(x.roundName)}</div><div class="question">${esc(x.q)}</div><div class="opts">${x.o.map((o,i)=>`<div class="opt ${i===x.a?'correct wrong':''}">${String.fromCharCode(65+i)} · ${esc(o)}</div>`).join('')}</div><div class="answerBox"><b>RICHTIG: ${String.fromCharCode(65+x.a)} · ${esc(x.o[x.a])}</b><br><span class="muted">${esc(x.e)}</span></div>`;if(host){$('#hostControls').innerHTML=`${state.reviewIndex>0?'<button onclick="send(\'reviewPrev\')">← ZURÜCK</button>':''}<button class="primary" onclick="send('reviewNext')">${state.reviewIndex===FLAT.length-1?'SIEGEREHRUNG 🏆':'NÄCHSTE AUFLÖSUNG →'}</button>`;$('#hostQuestion').innerHTML=body}else $('#playerView').innerHTML=body}
function renderFinal(host){const s=[...state.players].sort((a,b)=>(b.score??0)-(a.score??0)),top=s.slice(0,3);const podium=`<div class="center"><div class="eyebrow">FINAL HIGH SCORE</div><div class="winnerTitle">${esc(top[0]?.name||'WINNER')} WINS!</div><div class="podium">${top[1]?`<div class="pod second"><div class="medal">🥈</div><b>${esc(top[1].name)}</b><div>${top[1].score} PTS</div></div>`:'<div></div>'}${top[0]?`<div class="pod first"><div class="medal">🏆</div><b>${esc(top[0].name)}</b><div>${top[0].score} PTS</div></div>`:'<div></div>'}${top[2]?`<div class="pod third"><div class="medal">🥉</div><b>${esc(top[2].name)}</b><div>${top[2].score} PTS</div></div>`:'<div></div>'}</div>${s.slice(3).map((p,i)=>`<div class="rank">${i+4}. ${esc(p.name)} — <b>${p.score}</b></div>`).join('')}</div>`;if(host){$('#hostControls').innerHTML='';$('#hostQuestion').innerHTML=podium}else $('#playerView').innerHTML=podium}
function answer(i){selected=i;send('answer',{answer:i});render()}
function nextHost(){let r=state.roundIndex,q=state.questionIndex+1;if(q>=QUIZ[r].items.length){r++;q=0}if(r>=QUIZ.length)return send('finish');send('setQuestion',{roundIndex:r,questionIndex:q})}
function prevHost(){let r=state.roundIndex,q=state.questionIndex-1;if(q<0&&r>0){r--;q=QUIZ[r].items.length-1}if(q<0)q=0;send('setQuestion',{roundIndex:r,questionIndex:q})}
