import { QUIZ } from './quiz-data.js';
import { TEXT_CONFIG } from './text-config.js';
const CONFIG_KEY='nici40QuizConfigV1';
let ws,state,role=null,playerId=localStorage.playerId||null,playerToken=localStorage.playerToken||'',hostToken=localStorage.hostToken||'',roomCode=localStorage.roomCode||'',selected=null,timerLoop=null,reconnectTimer=null;
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
window.createGame=createGame;window.showJoin=showJoin;window.joinGame=joinGame;window.send=send;window.answer=answer;window.nextHost=nextHost;window.prevHost=prevHost;window.continueHost=continueHost;window.continueTeam=continueTeam;window.takeHostPrompt=takeHostPrompt;window.submitText=submitText;
function defaultItems(){return QUIZ.flatMap((round,ri)=>round.items.map((item,qi)=>({id:`${ri}-${qi}`,enabled:true,roundName:round.name,theme:round.theme,cat:item.cat||'POP',originalQ:item.q,q:item.q,options:[...item.o],answerIndex:item.a,explanation:item.e||'',answerMode:TEXT_CONFIG[item.q]?'open':'mc',canonical:TEXT_CONFIG[item.q]?.canonical||item.o[item.a],accept:TEXT_CONFIG[item.q]?.accept||[item.o[item.a]]})))}
function configuredGame(){try{const raw=JSON.parse(localStorage.getItem(CONFIG_KEY)||'null');if(Array.isArray(raw)&&raw.length)return{items:raw.filter(x=>x.enabled!==false),questionSeconds:180};if(raw&&Array.isArray(raw.items))return{items:raw.items.filter(x=>x.enabled!==false),questionSeconds:Math.max(15,Math.min(600,Math.round(Number(raw.settings?.questionSeconds)||180)))}}catch{}return{items:defaultItems(),questionSeconds:180}}
function configuredItems(){return configuredGame().items}
function refreshHome(){const cfg=configuredGame(),n=cfg.items.length;const tape=$('#questionCountTape');if(tape)tape.textContent=`${n} QUESTIONS`;const r=$('#recoveryActions');if(!r)return;let h='';if(localStorage.hostSnapshot||roomCode&&hostToken)h+='<button onclick="continueHost()">↻ LETZTES HOST-SPIEL FORTSETZEN</button>';if(localStorage.playerRoomCode&&playerId&&playerToken)h+='<button onclick="continueTeam()">↻ LETZTES TEAM FORTSETZEN</button>';r.innerHTML=h}
function connect(cb){clearTimeout(reconnectTimer);const proto=location.protocol==='https:'?'wss':'ws';ws=new WebSocket(`${proto}://${location.host}/ws`);ws.onopen=()=>{$('#status').textContent='ONLINE';cb&&cb()};ws.onclose=()=>{$('#status').textContent='SIGNAL LOST';if(role==='host'||role==='player')reconnectTimer=setTimeout(reconnectCurrent,1500)};ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='error'){if(m.code==='ROOM_NOT_FOUND'){if(role==='host'){const snap=getHostSnapshot();if(snap)return send('restoreHost',{snapshot:snap})}if(role==='player')return reconnectTimer=setTimeout(reconnectCurrent,1800)}return alert(m.message)}if(m.type==='created'||m.type==='restored'){role='host';roomCode=m.code;hostToken=m.hostToken;localStorage.roomCode=roomCode;localStorage.hostToken=hostToken;state=m.state;render()}if(m.type==='hostSnapshot'){localStorage.hostSnapshot=JSON.stringify(m.snapshot)}if(m.type==='joined'){role='player';playerId=m.playerId;playerToken=m.playerToken;localStorage.playerId=playerId;localStorage.playerToken=playerToken;localStorage.playerRoomCode=m.state.code;state=m.state;render()}if(m.type==='state'){state=m.state;render()}if(m.type==='answerAccepted'){selected=m.answer;render()}}}
function reconnectCurrent(){if(role==='host'&&roomCode&&hostToken)return connect(()=>send('rejoinHost',{code:roomCode,hostToken}));if(role==='player'&&localStorage.playerRoomCode&&playerId&&playerToken)return connect(()=>send('rejoinPlayer',{code:localStorage.playerRoomCode,playerId,playerToken}))}
function send(type,x={}){if(ws?.readyState===1)ws.send(JSON.stringify({type,...x}))}
function showJoin(){$('#joinBox').classList.remove('hidden')}
function createGame(mode='pub'){const cfg=configuredGame(),quiz=cfg.items;if(!quiz.length)return alert('Aktiviere zuerst mindestens eine Frage im Quiz-Admin.');connect(()=>send('create',{mode,quiz,questionSeconds:cfg.questionSeconds}))}
function joinGame(){const code=$('#code').value.trim().toUpperCase(),name=$('#name').value.trim();if(!code||!name)return alert('Code und Teamname eingeben.');localStorage.playerName=name;connect(()=>send('join',{code,name}))}
function getHostSnapshot(){try{return JSON.parse(localStorage.hostSnapshot||'null')}catch{return null}}
function continueHost(){const snap=getHostSnapshot();role='host';if(snap){roomCode=snap.code;hostToken=snap.hostToken;return connect(()=>send('restoreHost',{snapshot:snap}))}if(roomCode&&hostToken)return connect(()=>send('rejoinHost',{code:roomCode,hostToken}));alert('Kein Host-Backup vorhanden.')}
function continueTeam(){role='player';roomCode=localStorage.playerRoomCode||'';if(!roomCode||!playerId||!playerToken)return alert('Keine Team-Sitzung gespeichert.');connect(()=>send('rejoinPlayer',{code:roomCode,playerId,playerToken}))}
function takeHostPrompt(){const c=($('#code')?.value||prompt('Spielcode eingeben:')||'').trim().toUpperCase();if(!c)return;role='host';roomCode=c;connect(()=>send('takeHost',{code:c}))}
function current(){return state?.quiz?.[state.currentIndex]}
function render(){if(!state)return;$('#home').classList.add('hidden');applyEra();if(role==='host')renderHost();else renderPlayer();startTimerLoop()}
let lastEra=null;function applyEra(){const era=current()?.theme||state.quiz?.[state.reviewIndex]?.theme||'80s';document.body.dataset.era=era;const order=['80s','90s','00s','10s','20s'];document.querySelectorAll('.timeline .era').forEach((el,i)=>el.classList.toggle('active',order[i]===era));if(lastEra&&lastEra!==era){const names={'80s':'1980s','90s':'1990s','00s':'2000s','10s':'2010s','20s':'2020s'},subs={'80s':'PRESS PLAY ▶','90s':'POP CULTURE REWIND','00s':'Y2K MODE ACTIVATED','10s':'SWIPE TO CONTINUE →','20s':'NEXT ERA LOADING…'};const o=document.getElementById('eraTransition');if(o){document.getElementById('eraTransitionTitle').textContent=names[era];document.getElementById('eraTransitionSub').textContent=subs[era];o.classList.add('show');setTimeout(()=>o.classList.remove('show'),2600)}}lastEra=era}
function startTimerLoop(){clearInterval(timerLoop);if(state?.mode!=='pub'||state.phase!=='playing'||!state.questionEndsAt)return;updateTimers();timerLoop=setInterval(updateTimers,250)}
function timeLeft(){return Math.max(0,state.questionEndsAt-Date.now())}
function questionDuration(){return Math.max(15000,Number(state?.questionDurationMs)||180000)}
function fmt(ms){const total=Math.ceil(ms/1000),m=Math.floor(total/60),s=total%60;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function timerHTML(){const left=timeLeft(),dur=questionDuration(),pct=Math.max(0,Math.min(100,left/dur*100)),dangerAt=Math.min(30000,dur*.2);return `<div class="timerWrap"><div><div class="timerLabel">TIME REMAINING</div><div class="timer ${left<dangerAt?'danger':''}" data-timer>${fmt(left)}</div></div></div><div class="timerBar"><div data-timerbar style="width:${pct}%"></div></div>`}
function updateTimers(){const left=timeLeft(),dur=questionDuration(),pct=Math.max(0,Math.min(100,left/dur*100)),dangerAt=Math.min(30000,dur*.2);document.querySelectorAll('[data-timer]').forEach(el=>{el.textContent=fmt(left);el.classList.toggle('danger',left<dangerAt)});document.querySelectorAll('[data-timerbar]').forEach(el=>el.style.width=pct+'%')}
function playersHTML(host=false){if(!state.players.length)return '<p class="muted">Noch niemand da.</p>';return [...state.players].sort((a,b)=>(b.score??0)-(a.score??0)).map(p=>`<div class="playerRow"><span>${esc(p.name)} ${p.answered?'✓':''}${p.connected===false?' · offline':''}</span><span>${state.mode==='pub'&&state.phase!=='finished'?'<b>•••</b>':`<b>${p.score??0}</b>`}${host&&state.mode==='live'?`<span class="scoreBtns"><button onclick="send('score',{playerId:'${p.id}',delta:1})">+1</button><button onclick="send('score',{playerId:'${p.id}',delta:2})">+2</button><button onclick="send('score',{playerId:'${p.id}',delta:-1})">−1</button></span>`:''}</span></div>`).join('')}
function optionsHTML(item,interactive=false,me=null){if(item.answerMode==='open')return interactive?`<form class="textAnswerForm" onsubmit="submitText(event)"><input id="textAnswerInput" class="textAnswerInput" maxlength="120" autocomplete="off" placeholder="Antwort eingeben …" ${me?.answered?'disabled':''}><button class="primary textSubmit" type="submit" ${me?.answered?'disabled':''}>LOCK IN →</button></form><div class="textHint">Offene Antwort · KI bewertet sinnvolle Varianten.</div>`:`<div class="answerBox">OFFENE ANTWORT · KI-PRÜFUNG</div>`;return `<div class="opts">${item.options.map((o,i)=>interactive?`<button class="opt ${selected===i?'selected':''} ${state.revealed&&i===item.answerIndex?'correct':''}" ${me?.answered||state.revealed?'disabled':''} onclick="answer(${i})">${String.fromCharCode(65+i)} · ${esc(o)}</button>`:`<div class="opt ${state.revealed&&i===item.answerIndex?'correct':''}">${String.fromCharCode(65+i)} · ${esc(o)}</div>`).join('')}</div>`}
function qHTML(item){return `<div class="question" data-media-key="${esc(item.originalQ||item.q)}">${esc(item.q)}</div>`}
function renderHost(){
 $('#host').classList.remove('hidden');$('#player').classList.add('hidden');$('#bigCode').textContent=state.code;$('#modeBadge').textContent=state.mode==='pub'?`PUB MODE // ${state.totalQuestions} FRAGEN // ${fmt(questionDuration())}`:'LIVE MODE';$('#hostPlayers').innerHTML=playersHTML(true);
 if(state.phase==='lobby'){$('#hostControls').innerHTML=`<button class="primary" onclick="send('start')">START GAME</button>`;$('#hostQuestion').innerHTML=`<div class="center"><div class="phaseBanner">WAITING FOR PLAYERS</div><h2 class="waitingPulse">PRESS START WHEN READY</h2><p class="muted">${state.totalQuestions} ausgewählte Fragen · ${fmt(questionDuration())} pro Frage · Code <b>${state.code}</b></p><div class="answerBox">Host darf den Browser schließen. Das Spiel kann auf diesem Gerät aus dem lokalen Backup wiederhergestellt werden.</div></div>`;return}
 if(state.phase==='review')return renderReview(true);if(state.phase==='finished')return renderFinal(true);
 const item=current();if(state.mode==='pub'){$('#hostControls').innerHTML=`<button onclick="send('pubNext')">FRAGE BEENDEN →</button>`;$('#hostQuestion').innerHTML=`<div class="phaseBanner">QUESTION ${state.currentIndex+1} / ${state.totalQuestions}</div>${timerHTML()}<div class="eyebrow">${esc(item.roundName)} · ${esc(item.cat)}</div>${qHTML(item)}${optionsHTML(item,false)}<div class="answerBox"><b>${state.players.filter(p=>p.answered).length}/${state.players.length}</b> Teams haben geantwortet. Lösungen bleiben bis zur Auflösungsrunde gesperrt.</div>`;return}
 $('#hostControls').innerHTML=`<button onclick="prevHost()">←</button><button class="primary" onclick="send('reveal')">AUFLÖSEN</button><button onclick="nextHost()">WEITER →</button><button onclick="send('finish')">ENDE</button>`;$('#hostQuestion').innerHTML=`<div class="eyebrow">${esc(item.roundName)} · ${state.currentIndex+1}/${state.totalQuestions}</div>${qHTML(item)}${optionsHTML(item,false)}${state.revealed?revealHTML(item):''}`
}
function renderPlayer(){
 $('#player').classList.remove('hidden');$('#host').classList.add('hidden');const me=state.players.find(p=>p.id===playerId);$('#playerName').textContent=me?.name||localStorage.playerName||'TEAM';if(state.phase==='lobby')return $('#playerView').innerHTML=`<div class="center"><h2>READY ✓</h2><p class="muted">CODE ${state.code} // Warte auf den Host.</p></div>`;if(state.phase==='review')return renderReview(false);if(state.phase==='finished')return renderFinal(false);const item=current();if(!me?.answered)selected=null;$('#playerView').innerHTML=`${state.mode==='pub'?`<div class="phaseBanner">QUESTION ${state.currentIndex+1} / ${state.totalQuestions}</div>${timerHTML()}`:''}<div class="eyebrow">${esc(item.roundName)} · ${esc(item.cat)}</div>${qHTML(item)}${optionsHTML(item,true,me)}${me?.answered&&!state.revealed?'<div class="answerBox">LOCKED IN ✓<br><span class="muted">Antwort gespeichert. Bis zum Ende bleibt geheim, ob sie stimmt.</span></div>':''}${state.revealed?revealHTML(item):''}`
}
function revealHTML(item){if(item.answerMode==='open')return `<div class="answerBox"><b>RICHTIG: ${esc(item.canonical)}</b><br><span class="muted">${esc(item.explanation)}</span></div>`;return `<div class="answerBox"><b>RICHTIG: ${String.fromCharCode(65+item.answerIndex)} · ${esc(item.options[item.answerIndex])}</b><br><span class="muted">${esc(item.explanation)}</span></div>`}
function renderReview(host){const x=state.quiz[state.reviewIndex]||state.quiz[0];const answer=x.answerMode==='open'?`<div class="answerBox"><b>RICHTIG: ${esc(x.canonical)}</b><br><span class="muted">${esc(x.explanation)}</span></div>`:`<div class="opts">${x.options.map((o,i)=>`<div class="opt ${i===x.answerIndex?'correct wrong':''}">${String.fromCharCode(65+i)} · ${esc(o)}</div>`).join('')}</div><div class="answerBox"><b>RICHTIG: ${String.fromCharCode(65+x.answerIndex)} · ${esc(x.options[x.answerIndex])}</b><br><span class="muted">${esc(x.explanation)}</span></div>`;const body=`<div class="phaseBanner">ANSWER REVEAL</div><div class="reviewCount">AUFLÖSUNG ${state.reviewIndex+1} / ${state.totalQuestions}</div><div class="eyebrow">${esc(x.roundName)}</div>${qHTML(x)}${answer}`;if(host){$('#hostControls').innerHTML=`${state.reviewIndex>0?'<button onclick="send(\'reviewPrev\')">← ZURÜCK</button>':''}<button class="primary" onclick="send('reviewNext')">${state.reviewIndex===state.totalQuestions-1?'SIEGEREHRUNG 🏆':'NÄCHSTE AUFLÖSUNG →'}</button>`;$('#hostQuestion').innerHTML=body}else $('#playerView').innerHTML=body}
function renderFinal(host){const s=[...state.players].sort((a,b)=>(b.score??0)-(a.score??0)),top=s.slice(0,3);const podium=`<div class="center"><div class="eyebrow">FINAL HIGH SCORE</div><div class="winnerTitle">${esc(top[0]?.name||'WINNER')} WINS!</div><div class="podium">${top[1]?`<div class="pod second"><div class="medal">🥈</div><b>${esc(top[1].name)}</b><div>${top[1].score} PTS</div></div>`:'<div></div>'}${top[0]?`<div class="pod first"><div class="medal">🏆</div><b>${esc(top[0].name)}</b><div>${top[0].score} PTS</div></div>`:'<div></div>'}${top[2]?`<div class="pod third"><div class="medal">🥉</div><b>${esc(top[2].name)}</b><div>${top[2].score} PTS</div></div>`:'<div></div>'}</div>${s.slice(3).map((p,i)=>`<div class="rank">${i+4}. ${esc(p.name)} — <b>${p.score}</b></div>`).join('')}</div>`;if(host){$('#hostControls').innerHTML='';$('#hostQuestion').innerHTML=podium}else $('#playerView').innerHTML=podium}
function answer(i){selected=i;send('answer',{answer:i});render()}
function submitText(e){e.preventDefault();const input=$('#textAnswerInput'),value=input?.value.trim();if(!value)return;input.disabled=true;e.target.querySelector('button').disabled=true;send('textAnswer',{answer:value})}
function nextHost(){if(state.currentIndex>=state.totalQuestions-1)return send('finish');send('setQuestion',{index:state.currentIndex+1})}
function prevHost(){send('setQuestion',{index:Math.max(0,state.currentIndex-1)})}
refreshHome();