import { AUDIO_UPLOADS } from './media-config.js';
const list=document.querySelector('#audioList');
const dbOpen=()=>new Promise((resolve,reject)=>{const r=indexedDB.open('nici40-media',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('audio'))r.result.createObjectStore('audio')};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
const get=async key=>{const db=await dbOpen();return new Promise((resolve,reject)=>{const r=db.transaction('audio','readonly').objectStore('audio').get(key);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)})};
const put=async(key,file)=>{const db=await dbOpen();return new Promise((resolve,reject)=>{const r=db.transaction('audio','readwrite').objectStore('audio').put(file,key);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)})};
const del=async key=>{const db=await dbOpen();return new Promise((resolve,reject)=>{const r=db.transaction('audio','readwrite').objectStore('audio').delete(key);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)})};
async function render(){list.innerHTML='';for(const [i,x] of AUDIO_UPLOADS.entries()){const has=!!(await get(x.key));const row=document.createElement('div');row.className='uploadRow';row.innerHTML=`<div class="uploadMeta"><b>${String(i+1).padStart(2,'0')} · ${x.era}</b><strong>${x.label}</strong><small>Frage: ${x.question}</small></div><div class="uploadActions"><span class="uploadStatus ${has?'ok':''}">${has?'✓ GELADEN':'FEHLT'}</span><label class="uploadBtn">${has?'ERSETZEN':'DATEI WÄHLEN'}<input type="file" accept="audio/*" hidden></label>${has?'<button class="deleteAudio">LÖSCHEN</button>':''}</div>`;const inp=row.querySelector('input');inp.onchange=async()=>{if(inp.files[0]){await put(x.key,inp.files[0]);render()}};row.querySelector('.deleteAudio')?.addEventListener('click',async()=>{await del(x.key);render()});list.appendChild(row)}}
async function checkAi(){const box=document.querySelector('#aiStatus'),details=document.querySelector('#aiStatusDetails'),btn=document.querySelector('#recheckAi');box.className='aiStatus checking';box.innerHTML='<span class="aiDot"></span><div><strong>OPENAI WIRD GEPRÜFT …</strong><small>API-Key, Modell und Testaufruf</small></div>';details.textContent='';btn.disabled=true;try{const r=await fetch('/api/ai-status',{cache:'no-store'});const x=await r.json().catch(()=>({ok:false,error:'Ungültige Serverantwort'}));if(r.ok&&x.ok){box.className='aiStatus online';box.innerHTML='<span class="aiDot"></span><div><strong>OPENAI CONNECTED</strong><small>KI-Antwortprüfung ist einsatzbereit</small></div>';details.innerHTML=`<span>API-Key vorhanden ✓</span><span>Modell: <b>${x.model}</b></span><span>Testaufruf erfolgreich ✓</span><span>Antwortzeit: <b>${x.latencyMs} ms</b></span>`}else{box.className='aiStatus offline';box.innerHTML='<span class="aiDot"></span><div><strong>OPENAI OFFLINE</strong><small>KI-Prüfung ist derzeit nicht verfügbar</small></div>';details.innerHTML=`<span>API-Key: <b>${x.keyPresent?'vorhanden ✓':'fehlt ✕'}</b></span><span>Modell: <b>${x.model||'—'}</b></span><span>Fehler: <b>${x.error||`HTTP ${r.status}`}</b></span>`}}catch(e){box.className='aiStatus offline';box.innerHTML='<span class="aiDot"></span><div><strong>OPENAI OFFLINE</strong><small>Status-Endpunkt nicht erreichbar</small></div>';details.innerHTML=`<span>Fehler: <b>${e.message}</b></span>`}finally{btn.disabled=false}}
document.querySelector('#clearAll').onclick=async()=>{if(!confirm('Alle lokal gespeicherten Audios löschen?'))return;const db=await dbOpen();await new Promise((resolve,reject)=>{const r=db.transaction('audio','readwrite').objectStore('audio').clear();r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)});render()};document.querySelector('#recheckAi').onclick=checkAi;render();checkAi();
