import http from 'node:http';
import { WebSocketServer } from 'ws';
const ROUND_LENGTHS=[8,8,8,8,8];
const ANSWERS=[1,1,3,0,2,1,3,0,2,1,3,0,2,1,3,0,2,1,3,0,2,1,3,0,2,1,3,0,2,1,3,0,2,1,3,0,2,1,3,0];
function flatIndex(ri,qi){let n=qi;for(let i=0;i<ri;i++)n+=ROUND_LENGTHS[i]||0;return n}function coords(i){let r=0;while(i>=ROUND_LENGTHS[r]){i-=ROUND_LENGTHS[r];r++}return{roundIndex:r,questionIndex:i}}
const rooms=globalThis.__partyQuizRooms??new Map();globalThis.__partyQuizRooms=rooms;
function code(){const a='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let o='';for(let i=0;i<5;i++)o+=a[Math.floor(Math.random()*a.length)];return o}function id(){return Math.random().toString(36).slice(2,10)}function safeName(v,f='Team'){return String(v||f).replace(/[<>]/g,'').trim().slice(0,28)||f}function send(ws,type,payload={}){if(ws.readyState===1)ws.send(JSON.stringify({type,...payload}))}function currentFlatIndex(r){return flatIndex(r.roundIndex,r.questionIndex)}
function stateFor(r){const hide=r.mode==='pub'&&r.phase!=='finished';return{code:r.code,mode:r.mode,phase:r.phase,roundIndex:r.roundIndex,questionIndex:r.questionIndex,revealed:r.revealed,questionEndsAt:r.questionEndsAt,reviewIndex:r.reviewIndex,players:[...r.players.values()].map(p=>({id:p.id,name:p.name,score:hide?null:p.score,answered:p.answered,connected:p.connected!==false})),startedAt:r.startedAt}}
function broadcast(r,type='state',extra={}){const msg=JSON.stringify({type,state:stateFor(r),...extra});for(const ws of r.sockets)if(ws.readyState===1)ws.send(msg)}function roomOrFail(ws,c){const r=rooms.get(String(c||'').toUpperCase());if(!r)send(ws,'error',{message:'Spielcode nicht gefunden.'});return r}function clearTimer(r){if(r.timer){clearTimeout(r.timer);r.timer=null}}function resetAnswered(r){for(const p of r.players.values()){p.answered=false;p.answer=null}}
function nextPubQuestion(r){clearTimer(r);const i=currentFlatIndex(r);if(i<0||i>=ANSWERS.length-1){r.phase='review';r.reviewIndex=0;r.questionEndsAt=null;r.revealed=true;for(const p of r.players.values())p.score=Object.entries(p.answers||{}).reduce((s,[k,v])=>s+(ANSWERS[Number(k)]===v?1:0),0);broadcast(r);return}const n=coords(i+1);r.roundIndex=n.roundIndex;r.questionIndex=n.questionIndex;r.revealed=false;resetAnswered(r);startPubClock(r);broadcast(r)}function startPubClock(r){clearTimer(r);r.questionEndsAt=Date.now()+180000;r.timer=setTimeout(()=>nextPubQuestion(r),180050)}
const server=http.createServer((req,res)=>{res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({ok:true,rooms:rooms.size}))});const wss=new WebSocketServer({server});
wss.on('connection',ws=>{ws.meta={room:null,playerId:null,role:null};ws.on('message',raw=>{let m;try{m=JSON.parse(raw.toString())}catch{return send(ws,'error',{message:'Ungültige Nachricht.'})}
if(m.type==='create'){let c;do{c=code()}while(rooms.has(c));const hostToken=id()+id(),r={code:c,hostToken,hostSocket:ws,sockets:new Set([ws]),players:new Map(),mode:m.mode==='live'?'live':'pub',phase:'lobby',roundIndex:0,questionIndex:0,revealed:false,startedAt:null,questionEndsAt:null,reviewIndex:0,timer:null};rooms.set(c,r);ws.meta={room:c,playerId:null,role:'host'};send(ws,'created',{code:c,hostToken,state:stateFor(r)});return}
if(m.type==='rejoinHost'){const r=roomOrFail(ws,m.code);if(!r)return;if(m.hostToken!==r.hostToken)return send(ws,'error',{message:'Host-Berechtigung ungültig.'});r.hostSocket=ws;r.sockets.add(ws);ws.meta={room:r.code,playerId:null,role:'host'};return send(ws,'state',{state:stateFor(r)})}
if(m.type==='join'){const r=roomOrFail(ws,m.code);if(!r)return;const playerId=id(),p={id:playerId,name:safeName(m.name),score:0,answered:false,answer:null,answers:{},connected:true};r.players.set(playerId,p);r.sockets.add(ws);ws.meta={room:r.code,playerId,role:'player'};send(ws,'joined',{playerId,state:stateFor(r)});broadcast(r);return}
const r=roomOrFail(ws,ws.meta.room||m.code);if(!r)return;
if(m.type==='start'&&ws.meta.role==='host'){r.phase='playing';r.startedAt=Date.now();r.roundIndex=0;r.questionIndex=0;r.revealed=false;r.reviewIndex=0;for(const p of r.players.values()){p.score=0;p.answers={};p.answered=false;p.answer=null}if(r.mode==='pub')startPubClock(r);return broadcast(r)}
if(m.type==='answer'&&ws.meta.role==='player'&&r.phase==='playing'){const p=r.players.get(ws.meta.playerId);if(!p||p.answered||r.revealed)return;const a=Number(m.answer);if(!Number.isInteger(a)||a<0||a>3)return;p.answered=true;p.answer=a;p.answers[currentFlatIndex(r)]=a;send(ws,'answerAccepted',{answer:a});return broadcast(r,'state',{answerCount:[...r.players.values()].filter(x=>x.answered).length})}
if(ws.meta.role!=='host')return;if(m.type==='pubNext'&&r.mode==='pub'&&r.phase==='playing')return nextPubQuestion(r);if(m.type==='reviewNext'&&r.mode==='pub'&&r.phase==='review'){if(r.reviewIndex<ANSWERS.length-1){r.reviewIndex++;return broadcast(r)}r.phase='finished';return broadcast(r)}if(m.type==='reviewPrev'&&r.mode==='pub'&&r.phase==='review'){r.reviewIndex=Math.max(0,r.reviewIndex-1);return broadcast(r)}if(m.type==='setQuestion'&&r.mode==='live'){r.roundIndex=Math.max(0,Number(m.roundIndex)||0);r.questionIndex=Math.max(0,Number(m.questionIndex)||0);r.revealed=false;resetAnswered(r);return broadcast(r)}if(m.type==='reveal'&&r.mode==='live'){r.revealed=true;return broadcast(r)}if(m.type==='score'&&r.mode==='live'){const p=r.players.get(m.playerId);if(p)p.score+=Number(m.delta)||0;return broadcast(r)}if(m.type==='finish'){clearTimer(r);r.phase='finished';r.revealed=true;r.questionEndsAt=null;return broadcast(r)}});ws.on('close',()=>{const{room:rc,playerId}=ws.meta||{},r=rooms.get(rc);if(!r)return;r.sockets.delete(ws);if(playerId&&r.players.has(playerId)){r.players.get(playerId).connected=false;broadcast(r)}})});export default server;
