import http from 'node:http';
import { WebSocketServer } from 'ws';
import { QUIZ } from '../quiz-data.js';
import { TEXT_CONFIG } from '../text-config.js';

const DEFAULT_QUIZ=QUIZ.flatMap((round,ri)=>round.items.map((item,qi)=>({id:`${ri}-${qi}`,roundIndex:ri,questionIndex:qi,roundName:round.name,theme:round.theme,originalQ:item.q,q:item.q,cat:item.cat||'POP',options:[...item.o],answerIndex:item.a,explanation:item.e||'',answerMode:TEXT_CONFIG[item.q]?'open':'mc',canonical:TEXT_CONFIG[item.q]?.canonical||item.o[item.a],accept:TEXT_CONFIG[item.q]?.accept||[item.o[item.a]]})));
const rooms=globalThis.__partyQuizRooms??new Map();globalThis.__partyQuizRooms=rooms;
const DEFAULT_QUESTION_MS=180000;
function code(){const a='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let o='';for(let i=0;i<5;i++)o+=a[Math.floor(Math.random()*a.length)];return o}
function id(){return Math.random().toString(36).slice(2,10)}
function safeName(v,f='Team'){return String(v||f).replace(/[<>]/g,'').trim().slice(0,28)||f}
function cleanAnswer(v){return String(v??'').replace(/[\u0000-\u001f<>]/g,' ').trim().slice(0,120)}
function cleanQuestionMs(seconds){const n=Math.round(Number(seconds)||180);return Math.max(15,Math.min(600,n))*1000}
function send(ws,type,payload={}){if(ws?.readyState===1)ws.send(JSON.stringify({type,...payload}))}
function cleanQuiz(input){const src=Array.isArray(input)&&input.length?input:DEFAULT_QUIZ;return src.slice(0,60).map((x,i)=>{const opts=Array.isArray(x.options)?x.options.slice(0,4).map(v=>String(v).slice(0,120)):[];while(opts.length<4)opts.push('—');const ai=Math.max(0,Math.min(3,Number(x.answerIndex)||0));const mode=x.answerMode==='open'?'open':'mc';return{id:String(x.id||`q${i}`).slice(0,30),roundName:String(x.roundName||'Quiz').slice(0,40),theme:['80s','90s','00s','10s','20s'].includes(x.theme)?x.theme:'80s',originalQ:String(x.originalQ||x.q||'').slice(0,300),q:String(x.q||'Frage').slice(0,300),cat:String(x.cat||'POP').slice(0,30),options:opts,answerIndex:ai,explanation:String(x.explanation||'').slice(0,400),answerMode:mode,canonical:String(x.canonical||opts[ai]).slice(0,120),accept:Array.isArray(x.accept)?x.accept.slice(0,20).map(v=>String(v).slice(0,120)):[String(x.canonical||opts[ai])]} });}
function currentItem(r){return r.quiz[r.currentIndex]||r.quiz[0]}
function stateFor(r){const hide=r.mode==='pub'&&r.phase!=='finished';return{code:r.code,mode:r.mode,phase:r.phase,currentIndex:r.currentIndex,reviewIndex:r.reviewIndex,revealed:r.revealed,questionEndsAt:r.questionEndsAt,questionDurationMs:r.questionMs,totalQuestions:r.quiz.length,quiz:r.quiz,players:[...r.players.values()].map(p=>({id:p.id,name:p.name,score:hide?null:p.score,answered:p.answered,connected:p.connected!==false})),startedAt:r.startedAt}}
function snapshot(r){return{version:3,code:r.code,hostToken:r.hostToken,mode:r.mode,phase:r.phase,currentIndex:r.currentIndex,reviewIndex:r.reviewIndex,revealed:r.revealed,questionEndsAt:r.questionEndsAt,questionStartedAt:r.questionStartedAt,questionDurationMs:r.questionMs,startedAt:r.startedAt,quiz:r.quiz,players:[...r.players.values()].map(p=>({id:p.id,token:p.token,name:p.name,score:p.score,answered:p.answered,answer:p.answer,answers:p.answers||{},connected:false}))}}
function sendSnapshot(r){send(r.hostSocket,'hostSnapshot',{snapshot:snapshot(r)})}
function broadcast(r,type='state',extra={}){const msg=JSON.stringify({type,state:stateFor(r),...extra});for(const ws of r.sockets)if(ws.readyState===1)ws.send(msg);sendSnapshot(r)}
function roomOrFail(ws,c){const r=rooms.get(String(c||'').toUpperCase());if(!r)send(ws,'error',{message:'Spielcode nicht gefunden.',code:'ROOM_NOT_FOUND'});return r}
function clearTimer(r){if(r.timer){clearTimeout(r.timer);r.timer=null}}
function resetAnswered(r){for(const p of r.players.values()){p.answered=false;p.answer=null}}
function norm(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ß/g,'ss').replace(/[^a-z0-9]+/g,' ').trim()}
function levenshtein(a,b){if(a===b)return 0;if(!a.length)return b.length;if(!b.length)return a.length;let prev=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){const cur=[i];for(let j=1;j<=b.length;j++)cur[j]=Math.min(cur[j-1]+1,prev[j]+1,prev[j-1]+(a[i-1]===b[j-1]?0:1));prev=cur}return prev[b.length]}
function localJudge(answer,item){const a=norm(answer);if(!a)return false;const accepted=[item.canonical,...(item.accept||[])];for(const x of accepted){const n=norm(x);if(a===n)return true;if(Math.min(a.length,n.length)>=6&&levenshtein(a,n)<=2)return true}return null}
async function aiJudge(item,answer){if(!process.env.OPENAI_API_KEY)return null;try{const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${process.env.OPENAI_API_KEY}`},body:JSON.stringify({model:process.env.OPENAI_JUDGE_MODEL||'gpt-5.6-luna',store:false,reasoning:{effort:'none'},max_output_tokens:16,input:[{role:'developer',content:'Du bewertest Antworten in einem Partyquiz. Entscheide nur, ob die Antwort die erwartete Lösung eindeutig bezeichnet. Akzeptiere Tippfehler, Kurzformen, deutsche/englische Titel und offensichtliche Varianten. Akzeptiere keine nur thematisch verwandten Antworten. Antworte ausschließlich mit CORRECT oder WRONG.'},{role:'user',content:`Frage: ${item.q}\nErwartete Lösung: ${item.canonical}\nAntwort des Teams: ${answer}`} ]})});if(!response.ok)return null;const data=await response.json();const text=(data.output||[]).flatMap(x=>x.content||[]).filter(x=>x.type==='output_text').map(x=>x.text).join(' ').trim().toUpperCase();if(text.includes('CORRECT'))return true;if(text.includes('WRONG'))return false;return null}catch{return null}}
function pointsFor(r,correct,elapsed){if(!correct)return 0;const duration=Math.max(15000,r.questionMs||DEFAULT_QUESTION_MS);const speed=Math.round(300*Math.max(0,1-Math.min(duration,Math.max(0,elapsed))/duration));return 700+speed}
function recordResult(r,p,key,value,correct,elapsed,source){const points=pointsFor(r,correct,elapsed);p.answers[key]={value,correct,elapsed,points,source};p.score=(p.score||0)+points;return points}
function schedulePub(r){clearTimer(r);if(r.phase!=='playing'||r.mode!=='pub')return;const duration=r.questionMs||DEFAULT_QUESTION_MS;let remaining=(r.questionEndsAt||Date.now()+duration)-Date.now();if(remaining<=0){const jumps=Math.floor((-remaining)/duration)+1;r.currentIndex+=jumps;if(r.currentIndex>=r.quiz.length){r.currentIndex=Math.max(0,r.quiz.length-1);r.phase='review';r.reviewIndex=0;r.questionEndsAt=null;r.revealed=true;return broadcast(r)}r.questionEndsAt=(r.questionEndsAt||Date.now())+jumps*duration;r.questionStartedAt=r.questionEndsAt-duration;resetAnswered(r);remaining=r.questionEndsAt-Date.now()}r.timer=setTimeout(()=>nextPubQuestion(r),Math.max(50,remaining+50))}
function startPubQuestion(r){clearTimer(r);const duration=r.questionMs||DEFAULT_QUESTION_MS;r.questionStartedAt=Date.now();r.questionEndsAt=r.questionStartedAt+duration;r.timer=setTimeout(()=>nextPubQuestion(r),duration+50)}
function nextPubQuestion(r){clearTimer(r);if(r.currentIndex>=r.quiz.length-1){r.phase='review';r.reviewIndex=0;r.questionEndsAt=null;r.revealed=true;return broadcast(r)}r.currentIndex++;r.revealed=false;resetAnswered(r);startPubQuestion(r);broadcast(r)}
function makeRoom(c,hostToken,mode,quiz,questionSeconds=180){return{code:c,hostToken,hostSocket:null,sockets:new Set(),players:new Map(),quiz:cleanQuiz(quiz),questionMs:cleanQuestionMs(questionSeconds),mode:mode==='live'?'live':'pub',phase:'lobby',currentIndex:0,reviewIndex:0,revealed:false,startedAt:null,questionStartedAt:null,questionEndsAt:null,timer:null}}
function restoreRoom(s){const r=makeRoom(String(s.code||'').toUpperCase(),String(s.hostToken||id()+id()),s.mode,s.quiz,(Number(s.questionDurationMs)||DEFAULT_QUESTION_MS)/1000);r.phase=['lobby','playing','review','finished'].includes(s.phase)?s.phase:'lobby';r.currentIndex=Math.max(0,Math.min(r.quiz.length-1,Number(s.currentIndex)||0));r.reviewIndex=Math.max(0,Math.min(r.quiz.length-1,Number(s.reviewIndex)||0));r.revealed=!!s.revealed;r.startedAt=Number(s.startedAt)||null;r.questionStartedAt=Number(s.questionStartedAt)||null;r.questionEndsAt=Number(s.questionEndsAt)||null;for(const raw of Array.isArray(s.players)?s.players:[]){const p={id:String(raw.id||id()),token:String(raw.token||id()+id()),name:safeName(raw.name),score:Number(raw.score)||0,answered:!!raw.answered,answer:raw.answer??null,answers:raw.answers&&typeof raw.answers==='object'?raw.answers:{},connected:false};r.players.set(p.id,p)}return r}

const server=http.createServer((req,res)=>{res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({ok:true,rooms:rooms.size,aiJudge:!!process.env.OPENAI_API_KEY}))});
const wss=new WebSocketServer({server});
wss.on('connection',ws=>{ws.meta={room:null,playerId:null,role:null};ws.on('message',async raw=>{let m;try{m=JSON.parse(raw.toString())}catch{return send(ws,'error',{message:'Ungültige Nachricht.'})}
 if(m.type==='create'){let c;do{c=code()}while(rooms.has(c));const hostToken=id()+id(),r=makeRoom(c,hostToken,m.mode,m.quiz,m.questionSeconds);rooms.set(c,r);r.hostSocket=ws;r.sockets.add(ws);ws.meta={room:c,playerId:null,role:'host'};send(ws,'created',{code:c,hostToken,state:stateFor(r)});sendSnapshot(r);return}
 if(m.type==='restoreHost'){const s=m.snapshot;if(!s?.code||!s?.hostToken)return send(ws,'error',{message:'Kein gültiges Backup gefunden.'});const c=String(s.code).toUpperCase();let r=rooms.get(c);if(!r){r=restoreRoom(s);rooms.set(c,r);if(r.mode==='pub'&&r.phase==='playing')schedulePub(r)}else if(r.hostToken!==s.hostToken)return send(ws,'error',{message:'Host-Berechtigung ungültig.'});r.hostSocket=ws;r.sockets.add(ws);ws.meta={room:c,playerId:null,role:'host'};send(ws,'restored',{code:c,hostToken:r.hostToken,state:stateFor(r)});sendSnapshot(r);return broadcast(r)}
 if(m.type==='rejoinHost'){const r=roomOrFail(ws,m.code);if(!r)return;if(m.hostToken!==r.hostToken)return send(ws,'error',{message:'Host-Berechtigung ungültig.'});r.hostSocket=ws;r.sockets.add(ws);ws.meta={room:r.code,playerId:null,role:'host'};send(ws,'restored',{code:r.code,hostToken:r.hostToken,state:stateFor(r)});sendSnapshot(r);return}
 if(m.type==='takeHost'){const r=roomOrFail(ws,m.code);if(!r)return;r.hostToken=id()+id();r.hostSocket=ws;r.sockets.add(ws);ws.meta={room:r.code,playerId:null,role:'host'};send(ws,'restored',{code:r.code,hostToken:r.hostToken,state:stateFor(r)});sendSnapshot(r);return broadcast(r)}
 if(m.type==='join'){const r=roomOrFail(ws,m.code);if(!r)return;const playerId=id(),token=id()+id(),p={id:playerId,token,name:safeName(m.name),score:0,answered:false,answer:null,answers:{},connected:true};r.players.set(playerId,p);r.sockets.add(ws);ws.meta={room:r.code,playerId,role:'player'};send(ws,'joined',{playerId,playerToken:token,state:stateFor(r)});return broadcast(r)}
 if(m.type==='rejoinPlayer'){const r=roomOrFail(ws,m.code);if(!r)return;const p=r.players.get(String(m.playerId||''));if(!p||p.token!==m.playerToken)return send(ws,'error',{message:'Team-Sitzung konnte nicht wiederhergestellt werden.'});p.connected=true;r.sockets.add(ws);ws.meta={room:r.code,playerId:p.id,role:'player'};send(ws,'joined',{playerId:p.id,playerToken:p.token,state:stateFor(r)});return broadcast(r)}
 const r=roomOrFail(ws,ws.meta.room||m.code);if(!r)return;
 if(m.type==='start'&&ws.meta.role==='host'){r.phase='playing';r.startedAt=Date.now();r.currentIndex=0;r.revealed=false;r.reviewIndex=0;for(const p of r.players.values()){p.score=0;p.answers={};p.answered=false;p.answer=null}if(r.mode==='pub')startPubQuestion(r);else{r.questionStartedAt=Date.now();r.questionEndsAt=null}return broadcast(r)}
 if(m.type==='answer'&&ws.meta.role==='player'&&r.phase==='playing'){const p=r.players.get(ws.meta.playerId),item=currentItem(r);if(!p||p.answered||r.revealed||item.answerMode==='open')return;const a=Number(m.answer);if(!Number.isInteger(a)||a<0||a>3)return;const elapsed=Date.now()-(r.questionStartedAt||Date.now());p.answered=true;p.answer=a;recordResult(r,p,r.currentIndex,a,a===item.answerIndex,elapsed,'exact');send(ws,'answerAccepted',{answer:a});return broadcast(r,'state',{answerCount:[...r.players.values()].filter(x=>x.answered).length})}
 if(m.type==='textAnswer'&&ws.meta.role==='player'&&r.phase==='playing'){const p=r.players.get(ws.meta.playerId),item=currentItem(r);if(!p||p.answered||r.revealed||item.answerMode!=='open')return;const answer=cleanAnswer(m.answer);if(!answer)return;const elapsed=Date.now()-(r.questionStartedAt||Date.now());p.answered=true;p.answer=answer;send(ws,'answerAccepted',{answer});broadcast(r,'state',{answerCount:[...r.players.values()].filter(x=>x.answered).length});let correct=localJudge(answer,item),source='local';if(correct===null){correct=await aiJudge(item,answer);source=correct===null?'fallback':'openai'}if(correct===null)correct=false;recordResult(r,p,r.currentIndex,answer,correct,elapsed,source);sendSnapshot(r);return}
 if(ws.meta.role!=='host')return;
 if(m.type==='pubNext'&&r.mode==='pub'&&r.phase==='playing')return nextPubQuestion(r);
 if(m.type==='reviewNext'&&r.mode==='pub'&&r.phase==='review'){if(r.reviewIndex<r.quiz.length-1){r.reviewIndex++;return broadcast(r)}r.phase='finished';return broadcast(r)}
 if(m.type==='reviewPrev'&&r.mode==='pub'&&r.phase==='review'){r.reviewIndex=Math.max(0,r.reviewIndex-1);return broadcast(r)}
 if(m.type==='setQuestion'&&r.mode==='live'){r.currentIndex=Math.max(0,Math.min(r.quiz.length-1,Number(m.index)||0));r.revealed=false;resetAnswered(r);r.questionStartedAt=Date.now();return broadcast(r)}
 if(m.type==='reveal'&&r.mode==='live'){r.revealed=true;return broadcast(r)}
 if(m.type==='score'&&r.mode==='live'){const p=r.players.get(m.playerId);if(p)p.score+=Number(m.delta)||0;return broadcast(r)}
 if(m.type==='finish'){clearTimer(r);r.phase='finished';r.revealed=true;r.questionEndsAt=null;return broadcast(r)}
 });ws.on('close',()=>{const{room:rc,playerId}=ws.meta||{},r=rooms.get(rc);if(!r)return;r.sockets.delete(ws);if(playerId&&r.players.has(playerId)){r.players.get(playerId).connected=false;broadcast(r)}})});
export default server;